services:
  - type: web
    name: algoflow-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: node backend/server.js
    region: oregon
    plan: starter
    autoDeploy: false
    branch: main
    disk: 10GB
    healthCheckPath: /api/auth/config
    envVars:
      - key: DATABASE_URL
        fromDatabase: 
          name: algoflow-db
          property: connectionString
      - key: PGDATABASE
        fromDatabase:
          name: algoflow-db
          property: databaseName
      - key: JWT_SECRET
        generateValue: true

  - type: static
    name: algoflow-frontend
    buildCommand: npm install && npm run build
    publishPath: dist
    region: oregon
    plan: starter
    autoDeploy: false
    branch: main
